[package]
name = "cairo_blake2d"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
# Alexandria standard library
alexandria_math = "0.7.0"
alexandria_data_structures = "0.7.0"

[dev-dependencies]
cairo_test = "2.8.2"